In [1]:
!pip3 install kaggle

  Using cached https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/6c/4b/c38b5144cf167c4f52288517436ccafefe9dc01b8d1c190e18a6b154cd4a/tqdm-4.31.1-py2.py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/60/75/f692a584e85b7eaba0e03827b3d51f45f571c2e793dd731e598828d380aa/certifi-2019.3.9-py2.py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
  Using cached https://files.pythonhosted.org/pac

In [1]:
import kaggle

In [2]:
import os
import glob
import zipfile
import functools

import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
mpl.rcParams['axes.grid'] = False
mpl.rcParams['figure.figsize'] = (12,12)

from sklearn.model_selection import train_test_split
import matplotlib.image as mpimg
import pandas as pd
from PIL import Image

In [3]:
import tensorflow as tf
import tensorflow.contrib as tfcontrib
from tensorflow.python.keras import layers
from tensorflow.python.keras import losses
from tensorflow.python.keras import models
from tensorflow.python.keras import backend as K  

In [4]:
import os
# upload the kaggle.json to /home/jupyter/.kaggle/.

In [5]:
import kaggle

In [6]:
competition_name = 'dstl-satellite-imagery-feature-detection'
#kaggle competitions download -c dstl-satellite-imagery-feature-detection

In [ ]:
# Download data from Kaggle and unzip the files of interest. 
def load_data_from_zip(competition, file):
  with zipfile.ZipFile(os.path.join(competition, file), "r") as zip_ref:
    unzipped_file = zip_ref.namelist()[0]
    zip_ref.extractall(competition)

def get_data(competition):
    kaggle.api.competition_download_files(competition, competition)
    load_data_from_zip(competition, 'sixteen_band.zip')
    load_data_from_zip(competition, 'three_band.zip')
    load_data_from_zip(competition, 'train_geojson_v3.zip')
    load_data_from_zip(competition_name, 'train_wkt_v4.csv.zip')
    load_data_from_zip(competition_name, 'grid_sizes.csv.zip')
    load_data_from_zip(competition_name, 'sample_submission.csv.zip')

In [ ]:
get_data(competition_name)
# this takes about 60 minutes there is 20GB of data

In [8]:
!pip3 install tifffile

  Using cached https://files.pythonhosted.org/packages/ea/01/e69e5f741653121a0b60de5ba03cebbec3fd517ac0791d6530e56d9d06b0/tifffile-2019.3.8-py2.py3-none-any.whl
  Using cached https://files.pythonhosted.org/packages/e3/18/4f013c3c3051f4e0ffbaa4bf247050d6d5e527fe9cb1907f5975b172f23f/numpy-1.16.2-cp35-cp35m-manylinux1_x86_64.whl


In [ ]:
!pip3 install descartes

In [9]:
!pip3 install shapely

    100% |████████████████████████████████| 1.5MB 931kB/s 


In [20]:
from utils import data_utils, train_utils

In [25]:
#whoa! Are you sure - this takes a day last time I ran it!
!pwd

/home/jupyter/dstl_unet


In [31]:
!cd /home/jupyter/dstl_unet/utils

In [ ]:
run /home/jupyter/dstl_unet/utils/align_images.py

Align two rasters for 6010_1_2_M: cc:0.9560109305832611
warp matrix: 
[[ 1.0000000e+00 -5.3159874e-05 -2.1118374e+00]
 [ 5.3159874e-05  1.0000000e+00 -1.6461596e+00]]
Align two rasters for 6010_1_2_A: cc:0.7562650947897455
warp matrix: 
[[ 1.0000000e+00 -1.4252675e-04 -1.8752275e+01]
 [ 1.4252675e-04  1.0000000e+00  1.4256360e+01]]
Align two rasters for 6010_4_2_M: cc:0.9637410336078941
warp matrix: 
[[ 1.0000000e+00 -1.7019949e-04 -2.1078336e+00]
 [ 1.7019949e-04  1.0000000e+00 -5.7248658e-01]]
Align two rasters for 6010_4_2_A: cc:0.807989233433795
warp matrix: 
[[ 1.0000000e+00  2.4852898e-06 -1.8916107e+01]
 [-2.4852898e-06  1.0000000e+00  9.0697565e+00]]
Align two rasters for 6010_4_4_M: cc:0.9565304672908258
warp matrix: 
[[ 1.0000000e+00 -2.5203775e-05 -1.6531088e+00]
 [ 2.5203775e-05  1.0000000e+00 -2.8474563e-01]]
Align two rasters for 6010_4_4_A: cc:0.7961287336425549
warp matrix: 
[[ 1.0000000e+00  6.9238158e-05 -1.2039807e+01]
 [-6.9238158e-05  1.0000000e+00  1.0237100e+01]]